#!/bin/bash

# This test mostly checks that the scripts run.
#
# The test passes if it prints nothing to stderr.

FILE=testpofile.da.po
DIFF1=old.po
DIFF2=new.po

OUT=output.txt

echo -n > $OUT

gtgrep -i hello -s hej $FILE >> $OUT

poabc $FILE >> $OUT
poabc sdfkjsdfkj 2> /dev/null

gtxml $FILE >> $OUT

podiff --relax $DIFF1 $DIFF2 >> $OUT

poselect -ft $FILE >> $OUT
