#!/bin/bash

# This test mostly checks that the scripts run.
#
# The test passes if it prints nothing to stderr.

FILE=testpofile.da.po
DIFF1=old.po
DIFF2=new.po

OUT=output.txt

echo -n > $OUT

echo gtgrep
gtgrep -i hello -s hej $FILE >> $OUT

echo poabc
poabc $FILE >> $OUT
poabc sdfkjsdfkj 2> /dev/null

echo gtxml
gtxml $FILE >> $OUT

echo podiff
podiff --relax $DIFF1 $DIFF2 >> $OUT
# Podiff test for files with different encodings

echo gtcat
gtcat --encode ISO-8859-1 old.po|podiff -r - new.po > /dev/null

echo poselect
poselect -ft $FILE >> $OUT
