language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies.
# pip install -r requirements.txt  is run automatically
install:
  - pip install -e .
# command to run tests
script: py.test -vv .

sudo: false