#!/bin/bash

# This test mostly checks that the scripts run.
#
# The test passes if it prints nothing to stderr.

FILE=testpofile.da.po
DIFF1=old.po
DIFF2=new.po

OUT=output.txt

echo -n > $OUT

echo gtcat
gtcat --encode ISO-8859-1 old.po|podiff -r - new.po > /dev/null

echo gtcheckargs
gtcheckargs $FILE >> $OUT

echo gtcompare
gtcompare $FILE $FILE >> $OUT

echo gtgrep
gtgrep -i hello -s hej $FILE >> $OUT

echo gtmerge
gtmerge $FILE $FILE >> $OUT

echo gtprevmsgdiff
gtprevmsgdiff $FILE >> $OUT

echo gtxml
gtxml $FILE >> $OUT

echo poabc
poabc $FILE >> $OUT
poabc sdfkjsdfkj 2> /dev/null

echo podiff
podiff --relax $DIFF1 $DIFF2 >> $OUT
# Podiff test for files with different encodings

echo popatch
popatch testpofile.da.po testpodiff.podiff > patched.po && gtcat patched.po > /dev/null
popatch --new testpodiff.podiff > patched.new.po
popatch --old testpodiff.podiff > patched.old.po
podiff -rf patched.old.po patched.new.po > patched.diffed.podiff
# patched.diffed.podiff should now be identical to the original diff
# ....except line numbers.

echo poselect
poselect -ft $FILE >> $OUT
